version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3307:3306"